"""Plain English for bot status codes and sub codes.

From docs/bot-status-change-events and docs/sub-codes. Recall adds codes without notice, so describe()
falls back to the raw value for anything not listed here.
"""

CODES = {
    "ready": "Created, waiting to join",
    "joining_call": "Joining the call",
    "in_waiting_room": "In the waiting room",
    "in_call_not_recording": "In the call, not recording yet",
    "recording_permission_allowed": "Recording permission granted",
    "recording_permission_denied": "Recording permission denied",
    "in_call_recording": "In the call and recording",
    "call_ended": "Call ended",
    "done": "Done, media uploaded",
    "fatal": "Failed",
    "breakout_room_entered": "Entered a breakout room",
    "breakout_room_left": "Left a breakout room",
    "breakout_room_opened": "A breakout room opened",
    "breakout_room_closed": "A breakout room closed",
    "media_expired": "Media expired",
}

SUB_CODES = {
    # Recording Permission Denied Sub Codes
    "zoom_local_recording_disabled": "The meeting host has their global user-level local recording setting disabled.",
    "zoom_local_recording_request_disabled": "The meeting host has local recording enabled but turned off the option that lets hosts grant participants permission to record locally.",
    "zoom_local_recording_request_disabled_by_host": "The meeting host has disabled participants from requesting local recording permission or has denied all future requests.",
    "zoom_bot_in_waiting_room": "The bot is in the waiting room due to which local recording cannot be requested.",
    "zoom_host_not_present": "The host was not present in the meeting when the bot requested local recording permission.",
    "zoom_local_recording_request_denied_by_host": "The host denied the bot's local recording request or if the host hasn't responded to the local recording request within 60s.",
    "zoom_local_recording_denied": "The bot sent a recording permission request to the host, but did not receive a response and the request timed out.",
    "zoom_local_recording_grant_not_supported": "The meeting host is using Zoom Room or other Zoom client that does not support local recording permission.",
    "zoom_sdk_key_blocked_by_host_admin": "The Zoom SDK key used by the bot is blocked by the Zoom user's workspace admin.",
    "zoom_invalid_email": "Ensure that a valid zoom.user_email was provided with no invisible characters.",
    # Call Ended Sub Codes
    "call_ended_by_host": "The call has been ended by the meeting host.",
    "call_ended_by_platform_idle": "The call has been ended by the meeting platform, because it was idle.",
    "call_ended_by_platform_max_length": "The call has been ended by the meeting platform because it reached the maximum meeting length.",
    "call_ended_by_platform_waiting_room_timeout": "The bot could not join the call because meeting platform's maximum waiting room time exceeded.",
    "timeout_exceeded_waiting_room": "The bot left the call because it was in the waiting room for too long.",
    "timeout_exceeded_noone_joined": "The bot left the call because nobody joined the call for too long.",
    "timeout_exceeded_everyone_left": "The bot left the call because everyone else left.",
    "timeout_exceeded_silence_detected": "The bot left the call because all other participants were likely bots based off continuous silence detection heuristic.",
    "timeout_exceeded_only_bots_detected_using_participant_names": "The bot left the call because all other participants were likely bots based off participant names heuristic.",
    "timeout_exceeded_only_bots_detected_using_participant_events": "The bot left the call because all other participants were likely bots based off participant events heuristic.",
    "timeout_exceeded_in_call_not_recording": "The bot left the call because it never started recording e.g.",
    "timeout_exceeded_in_call_recording": "The bot left the call because it exceeded the timeout set in automatic_leave.in_call_recording_timeout .",
    "timeout_exceeded_recording_permission_denied": "The bot left the call because it exceed the timeout set in recording_permission_denied_timeout.",
    "timeout_exceeded_max_duration": "The bot exceeded its maximum duration it can remain in a call.",
    "bot_kicked_from_call": "The bot was removed from the call by the host.",
    "bot_kicked_from_waiting_room": "The bot was removed from the waiting room by the host.",
    "bot_received_leave_call": "The bot received leave call request.",
    "meeting_not_started": "The bot was unable to join the meeting because it hasn't started yet.",
    "breakout_room_not_open": "The bot was created with join_specific_room configured and the room is not open to join (or closes).",
    # Fatal Sub Codes
    "bot_errored": "The bot ran into an unexpected error.",
    "meeting_not_found": "No meeting was found at the given link.",
    "meeting_not_accessible": "This meeting is not accessible.",
    "meeting_requires_registration": "The meeting requires registration.",
    "meeting_requires_sign_in": "The meeting can only be joined by signed in users.",
    "meeting_link_expired": "The meeting link has expired.",
    "meeting_link_invalid": "The meeting does not exist or the link is invalid.",
    "meeting_password_incorrect": "The meeting password is incorrect.",
    "meeting_locked": "The meeting is locked.",
    "meeting_full": "The meeting is full.",
    "meeting_ended": "The bot attempted to join a meeting that has already ended and can no longer be joined.",
    "failed_to_launch_in_time": "The bot took too long to launch due to an error on Recall's infrastructure.",
    # Zoom Fatal Sub Codes
    "zoom_sdk_credentials_missing": "The bot was not able to join because Zoom SDK credentials were not configured.",
    "zoom_sdk_update_required": "A newer version of the Zoom SDK is required to join this meeting.",
    "zoom_sdk_app_not_published": "The SDK credentials configured in Recall dashboard have not been approved by Zoom.",
    "zoom_email_blocked_by_admin": "The Zoom account this bot is joining from has been disallowed to join this meeting by the Zoom workspace administrator.",
    "zoom_registration_required": "The bot failed to join because registration is required for this Zoom meeting.",
    "zoom_captcha_required": "The bot failed to join because captcha is required for this Zoom meeting.",
    "zoom_account_blocked": "Someone previously removed the signed-in Zoom bot and selected the 'Once removed, BOT_NAME will not be able to rejoin the meeting.' option.",
    "zoom_invalid_join_token": "Zoom's SDK rejected the join token provided by the bot.",
    "zoom_token_expired": "The provided token (such as a Join Token for Local Recording or ZAK token) was expired when the bot attempted to use it to join the Zoom meeting.",
    "zoom_invalid_signature": "The Zoom SDK was not able to generate a valid meeting-join signature.",
    "zoom_internal_error": "The bot errored due to an internal Zoom error.",
    "zoom_join_timeout": "The request to join the Zoom meeting timed out.",
    "zoom_email_required": "The bot failed to join because providing an email is required to join this Zoom meeting.",
    "zoom_web_disallowed": "The Zoom meeting host has disallowed joining from the web which prevents the bot from joining the meeting.",
    "zoom_connection_failed": "The bot failed to join the meeting due to a internal server error on Zoom's end.",
    "zoom_error_multiple_device_join": "The bot failed to join the meeting due to another participant with the same credentials having joined the meeting.",
    "zoom_meeting_not_accessible": "The Zoom meeting was not accessible for the bot.",
    "zoom_meeting_host_inactive": "The request to join the Zoom meeting failed, as the meeting host has been disabled or restricted.",
    "zoom_invalid_webinar_invite": "The invite to the Zoom webinar was invalid.",
    "zoom_another_meeting_in_progress": "This host has another meeting in progress.",
    "zoom_obf_user_not_in_meeting": "The Zoom user associated with the OBF token provided is not in the meeting.",
    "zoom_anonymous_join_not_allowed": "The bot attempted to join a Zoom meeting using SDK credentials, without passing in a ZAK token.",
    "zoom_obf_or_zak_missing_or_invalid": "The OBF or ZAK token that's passed to the bot is invalid.",
    "zoom_voice_recording_not_supported": "This bot attempted to join a Zoom meeting ID that corresponds to a Zoom Voice Recorder Summary, which can't be joined.",
    "zoom_bot_blocked": "The bot was disallowed from joining the meeting.",
    "zoom_authorized_participants_only": "This Zoom meeting only allows authorized participants.",
    "missing_webinar_license": "The host of this zoom webinar is either missing a webinar license, or has a webinar license that is no longer valid.",
    # Google Meet Fatal Sub Codes
    "google_meet_internal_error": "The bot errored due to a Google Meet internal issue.",
    "google_meet_sign_in_failed": "The bot was not able to sign in to google.",
    "google_meet_sign_in_captcha_failed": "The bot was not able to sign in to google because of captcha.",
    "google_meet_bot_blocked": "The bot was disallowed from joining the meeting.",
    "google_meet_sso_sign_in_failed": "The bot was not able to sign in to google with SSO.",
    "google_meet_sign_in_missing_login_credentials": "The bot was not able to sign in to google because login credentials were not configured.",
    "google_meet_sign_in_missing_recovery_credentials": "The bot was not able to sign in to google because recovery credentials were not configured.",
    "google_meet_sso_sign_in_missing_login_credentials": "The bot was not able to sign in to google with SSO because login credentials were not configured.",
    "google_meet_sso_sign_in_missing_totp_secret": "The bot was not able to sign in in to google with SSO because TOTP secret was missing from password.",
    "google_meet_video_error": "The bot was not able to join the call due to Google Meet video error.",
    "google_meet_meeting_room_not_ready": "The bot was not able to join the call as the meeting room was not ready.",
    "google_meet_login_not_available": "There were not enough available logins (Google accounts) in the supplied google_login_group_id for the bot to use.",
    "google_meet_permission_denied_breakout": "The bot tried to join an active Google Meet breakout room and was rejected.",
    "google_meet_knocking_disabled": "The bot was unable to ask to join the meeting due to the settings of the host.",
    "google_meet_watermark_kicked": "The watermark feature in google meet was enabled mid-call and the bot was not signed in.",
    "google_meet_organisation_restricted": "The bot was unable to join because the call is restricted to members of the host organization.",
    "sso_login_account_disabled": "The Google account used for SSO has been disabled.",
    "sso_login_invalid_recipient": "Invalid SSO workspace domain.",
    "sso_not_configured": "Your domain is not configured to use Single Sign On.",
    # Teams Fatal Sub Codes
    "microsoft_teams_sign_in_credentials_missing": "The bot failed to join a Microsoft Teams meeting requiring all participants to be signed-in.",
    "microsoft_teams_call_dropped": "Microsoft Teams disconnected and the bot was unable to reconnect.",
    "microsoft_teams_sign_in_failed": "The bot failed to join a Microsoft Teams meeting requiring all participants to be signed-in.",
    "microsoft_teams_internal_error": "The bot errored due to a Microsoft Teams server error.",
    "microsoft_teams_captcha_error": "The bot failed to join due to captcha being enabled for anonymous participants.",
    "microsoft_teams_bot_not_invited": "The bot failed to join a Microsoft Teams meeting as it was not the account that was invited.",
    "microsoft_teams_breakout_room_unsupported": "The bot was moved to a Microsoft Teams breakout room, but they are not supported by Recall.",
    "microsoft_teams_townhall_meeting_not_supported": "The bot was added to a Microsoft Teams townhall meeting, but this type of meeting is not supported by Recall.",
    "microsoft_teams_event_not_started_for_external": "The bot failed to join a Microsoft Teams meeting that prevents external participants from joining before the event begins.",
    "microsoft_teams_2fa_required": "",
    "microsoft_teams_captions_failure": "The host had meeting captions disabled so the bot wasn't able generate them.",
    # Webex Fatal Sub Codes
    "webex_join_meeting_error": "The bot failed to join a Webex meeting because the meeting was invalid, or Webex credentials are not set up properly.",
    "webex_pin_required": "The bot failed to join a Webex meeting because the meeting required a pin.",
    "webex_password_required": "The bot failed to join a Webex meeting because the meeting required a password.",
    "webex_user_has_excessive_device_registrations": "There are too many bots currently in use.",
    "webex_service_app_unauthorized": "The service app is no longer authorized with Recall.ai.",
    # Zoom RTMS
    "rtms_signature_invalid": "Zoom did not accept the provided signature.",
    "zoom_rtms_duplicate_signal_request": "There is already a connection for this RTMS stream.",
    "zoom_rtms_invalid_stream_id": "The RTMS stream id was invalid.",
    "zoom_rtms_internal_exception": "There was an issue upstream from Zoom's RTMS service.",
    # Meet Media API
    "meet_media_space_not_found": "",
    "meet_media_unauthenticated": "",
    "meet_media_failed_precondition": "",
    "meet_media_sdp_negotiation_error": "",
    "meet_media_internal_error": "",
}


def describe(code, sub_code=None):
    text = CODES.get(code, code)
    if sub_code:
        text = f"{text}: {SUB_CODES.get(sub_code, sub_code)}"
    return text
